### ISSUE TITLE
Does not work on UK links

### ISSUE THREAD

**Issue by PCKid11** [Jdhaimson/smilealways#42]
**What I do:** I go to amazon.co.uk.

**What happens:** I continue to amazon.co.uk without being redirected.

**What should happen:** I get redirected to smile.amazon.co.uk.

Probably a 5 minute fix but I don't know how to use `git`.

**Comment by delitzer** [comment]
Thanks for flagging. Someone already submitted a pull request. I’ll test
this weekend and plan to push a new version to the Chrome Store on Tuesday.
With the two biggest shopping days of the year in the US being Friday and
Monday, I don’t want to run the risk of the update causing the extension to
get pulled due to recent policy changes until then.

**Comment by delitzer** [comment]
Pushed it.
