### ISSUE TITLE
SA gets stuck in a redirect loop if clicking a link to a product and the user is not signed into Amazon

### ISSUE THREAD

**Issue by Pseudogenesis** [Jdhaimson/smilealways#44]
I was accessing this link from a Google search page: https://www.amazon.com/ACCO-Loose-Binder-Capacity-Silver/dp/B00008XPLC

It's happened many different times with different links, but maybe this helps replicate the issue. [The error message looks pretty much exactly like this.](https://techwelkin.com/wp-content/uploads/2015/06/this-webpage-has-a-redirect-loop-techwelkin.jpg)

What solved it was going directly to Amazon.com, which properly redirected me to a sign-in page. After that, clicking the link at the top worked perfectly. Clearing all cookies did nothing, problem reoccurred immediately when I logged out of Amazon. 

Chrome Version 65.0.3325.181 (Official Build) (64-bit)
Windows 10 Pro
SmileAlways Version 1.0

**Comment by delitzer** [comment]
Thanks for reporting with details. I couldn't recreate this issue. When I click the link while logged out, I don't get redirected to the Smile version, but there's no redirect loop.

Are you sure you're not using a modified version of the extension from another source? The Chrome Web Store version (which is the current master version here) is v0.93; we still haven't hit version 1.0.

If that isn't it, could you list the other extensions you have installed? Sometimes these issues are caused by weird interactions with other extensions.

**Comment by Pseudogenesis** [comment]
I'm an idiot. I wasn't using SmileAlways, I was using [Always Smile](https://chrome.google.com/webstore/detail/always-smile/fpaapignoneonaghhkoddkghglbppdmg). 

Installed the proper extension and it behaves as expected. Thanks.
